### ISSUE TITLE
Integration with MySql.

### ISSUE THREAD

**Issue by mohamedriiyad** [IzyPro/WatchDog#101]
When I use mysql as DbDriverOption it throws an error :
_WatchDogDatabaseException: WatchDog Database Exception: Column length too big for column 'requestBody' (max = 16383); use BLOB or TEXT instead Ensure you have passed the right Database Driver Option or a proper connection string at .AddWatchDogServices() as well as all required parameters for the database connection string_

While my connection string is correct.
Can you provide me an answer and thank you for your effort and this great work.

**Comment by IzyPro** [comment]
We are closing this issue as it has been fixed
Kindly update the WatchDog package or run the SQL command to alter the column datatype if you would like to avoid data loss

**Comment by timothy-m-allen** [comment]
I'm still getting this error when trying to use MySQL, currently using version 1.4.6.

**Comment by IzyPro** [comment]
Hi @timothy-m-allen 

The issue has been fixed, as you can see from [here](https://github.com/IzyPro/WatchDog/blob/main/WatchDog/src/Data/ExternalDbContext.cs) that the datatype for MySQL requestBody is set to the maximum of type TEXT.

I suspect the WatchDog tables on your database were created with a previous version which is why you are still experiencing this issue. You can either

1. Delete the WatchDog table from your database and then launch your project with the latest version of WatchDog so that the table can be created again.
Con: Loss of data

2. Run the alter table command to change the datatype of the affected column in your database which in your case is ‘requestBody’.
Here’s what the command will look like:
ALTER TABLE WatchDog_WatchLogs
MODIFY requestBody TEXT(65535);

I hope this helps.

**Comment by timothy-m-allen** [comment]
I found the source of my issue. Will share here to save someone time that might also run into this issue.

My local MySQL settings were configured with "lower_case_table_names=1" which only allows lowercase characters in schema and table names. Therefore when WatchDog tried to create a table called "WatchDog_Logs" which included capital letters, it was throwing an error.

When I manually created the all three tables required by WatchDog it worked fine. Also changing the "lower_case_table_names=0" fixes the issue. 

Really enjoying using WatchDog, thank you for your great work!
